### PR TITLE
Views

### PR DESCRIPTION
**Pull request by hetrox8**
This branch's core goal is to :
1. Use preprocessed HTML file with embedded Ruby code.
2. Use layouts and templates for shared content.

The main language used to achieve this include 
1. Ruby 
2. Rails 
3. Html
4. Vanilla Javascript

### CODE REVIEW

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @hetrox8,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] You didn't document your work professionally:
   You have some poorly documented sections in your README file Like:
   - Elaborate on the `Project description` because you wrote a few words.
   - Add issues link to the `Contributions` section.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by hetrox8** [comment]
@Omar-Muhamad really bro i had been submitting this project the whole week..you know you could have just add optional changes..

**Comment by hetrox8** [comment]
## Changes made
1. Elaborate on the Project description
2. Add issues link to the Contributions section.

**Review by uwadonat — APPROVED** [review]
## Hi @hetrox8,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
- Correct workflow was used ✔️
- Well-organized and clean project ✔️
- No linter error ✔️
- Professional readme file ✔️
approv

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
